<?php
    $ratings = array(
        '<img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-half.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-half.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-half.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-half.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-empty.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-half.svg" alt="">',
        '<img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">
        <img src="assets/img/stars/star-full.svg" alt="">'
    );
?>